#!/bin/sh
SRCPATH="$( cd "$( dirname $(readlink -nf $0) )" && pwd )"

if [ ! -f "$SRCPATH"/bin/radiant ]; then
	printf "Map editor is not present, please run build_editor.sh\n"
	exit
fi

cd "$SRCPATH"/bin 

if [[ -z "${NUCLIDE_GDB}" ]]; then
	./radiant ../ $*
else
	gdb --args ./radiant ../ $*
fi



